from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from hypervisor.deployment_registry.local_targets import (
    local_target_to_module,
    local_target_to_relative_path,
)

from hypervisor.agent_describe.collect import (
    agent_kind,
    capability_backing_note,
    deployment_health_label,
    read_yaml,
    rel,
    skill_invoke_example,
)


@dataclass
class RenderContext:
    repo: Path
    selector: str
    deployment: Any
    agent_name: str
    agent_meta: dict[str, Any]
    contract_path: Path | None
    contract: dict[str, Any]
    is_operator: bool
    generated_meta: dict[str, Any]
    domain_pack: dict[str, Any] | None
    markpact_blocks: list[dict[str, str]]
    files: list[dict[str, str]]
    agent_caps: list[Any]
    all_deployments: list[Any]
    run_plan: dict[str, Any] | None
    registry: Any

    @property
    def kind(self) -> str:
        return agent_kind(self.deployment, is_operator=self.is_operator)


def render_markdown(ctx: RenderContext) -> str:
    sections = [
        _render_header(ctx),
        _render_contract(ctx),
        _render_capabilities(ctx),
        _render_domain_pack(ctx),
        _render_package(ctx),
        _render_deployments(ctx),
        _render_invocation(ctx),
        _render_architecture(ctx),
        _render_markpact_blocks(ctx),
        _render_registry(ctx),
    ]
    return "\n".join(section for section in sections if section) + "\n"


def _render_header(ctx: RenderContext) -> str:
    return "\n".join(
        [
            f"# Agent report: `{ctx.agent_name}`",
            "",
            f"Selector: `{ctx.selector}` · deployment: `{ctx.deployment.id}` · agent ref: `{ctx.deployment.agent_ref}`",
        ]
    )


def _contract_intro(ctx: RenderContext) -> list[str]:
    if ctx.is_operator:
        return [
            "Primary contract format is **operator YAML** under `agents/operators/*.yaml` "
            "(`kind: hypervisor.operator_agent`).",
        ]
    if ctx.kind == "custom":
        return [
            "Primary contract format is **YAML** under `contracts/agents/*.yaml` "
            "(resource-agent-factory schema).",
            "Custom packages under `agents/custom/*` are **hand-written** and are not "
            "regenerated by `resource-agent-factory` (no Markpact README blocks).",
        ]
    return [
        "Primary contract format is **YAML** under `contracts/agents/*.yaml` "
        "(resource-agent-factory schema).",
        "Generated packages embed **Markpact** provenance blocks in `README.md` "
        "(not the source contract file).",
    ]


def _render_contract(ctx: RenderContext) -> str:
    lines = ["", "## Contract", ""] + _contract_intro(ctx) + [""]
    if not ctx.contract_path:
        lines.append("- _No contract YAML found for this agent._")
        return "\n".join(lines)

    if ctx.is_operator:
        lines.extend(
            [
                f"- **Contract file:** `{rel(ctx.repo, ctx.contract_path)}`",
                f"- **Kind:** `{ctx.contract.get('kind', '—')}`",
                f"- **Title:** {ctx.agent_meta.get('title', '—')}",
                f"- **Description:** {ctx.agent_meta.get('description', '—')}",
                f"- **Runtime package:** `{ctx.agent_meta.get('runtime_package', '—')}`",
            ]
        )
        runtime = ctx.contract.get("runtime") or {}
        if runtime.get("health_uri"):
            lines.append(f"- **Health URI:** `{runtime['health_uri']}`")
        return "\n".join(lines)

    lines.extend(
        [
            f"- **Contract file:** `{rel(ctx.repo, ctx.contract_path)}`",
            f"- **Version:** `{ctx.agent_meta.get('version', '—')}`",
            f"- **Python package:** `{ctx.agent_meta.get('python_package', '—')}`",
            f"- **Description:** {ctx.agent_meta.get('description', '—')}",
        ]
    )
    if ctx.kind == "custom":
        lines.append(
            "- **Implementation:** hand-written FastAPI routes "
            "(capabilities served directly, no Resource Runtime proxy)"
        )
    else:
        lines.append(
            f"- **Runtime env:** `{ctx.agent_meta.get('runtime_url_env', 'RESOURCE_RUNTIME_URL')}` "
            f"→ `{ctx.agent_meta.get('runtime_url_default', 'http://localhost:8000')}`"
        )
    if ctx.kind == "generated" and ctx.generated_meta.get("contract_hash"):
        lines.append(f"- **Contract hash:** `{ctx.generated_meta['contract_hash']}`")
    if ctx.kind == "generated" and ctx.generated_meta.get("generator"):
        lines.append(f"- **Generator:** `{ctx.generated_meta['generator']}`")
    return "\n".join(lines)


def _render_capabilities(ctx: RenderContext) -> str:
    lines = ["", "## Capabilities (contract)", ""]
    if ctx.is_operator:
        op_caps = ctx.contract.get("capabilities") or []
        if not op_caps:
            lines.append("_No operator capabilities in contract._")
            return "\n".join(lines)
        lines.extend(["| Scheme | Operations | Adapters |", "|--------|------------|----------|"])
        for cap in op_caps:
            ops = ", ".join(cap.get("operations") or [])
            adapters = ", ".join(cap.get("adapters") or [])
            lines.append(f"| `{cap.get('scheme', '—')}` | {ops or '—'} | {adapters or '—'} |")
        return "\n".join(lines)

    caps = ctx.contract.get("capabilities") or []
    if not caps:
        lines.append("_No capabilities in contract._")
        return "\n".join(lines)
    lines.extend(
        [
            "| Name | Type | URI / command | Schema | Renderer |",
            "|------|------|---------------|--------|----------|",
        ]
    )
    for cap in caps:
        uri_or_cmd = cap.get("uri") or cap.get("command") or "—"
        lines.append(
            f"| `{cap.get('name', '—')}` | `{cap.get('type', '—')}` | `{uri_or_cmd}` | "
            f"`{cap.get('output_schema') or cap.get('input_schema') or '—'}` | `{cap.get('renderer') or '—'}` |"
        )
    return "\n".join(lines)


def _render_domain_pack(ctx: RenderContext) -> str:
    if not ctx.domain_pack:
        return ""
    lines = [
        "",
        "## Domain pack",
        "",
        f"- **Domain id:** `{ctx.domain_pack['id']}`",
        f"- **Path:** `{ctx.domain_pack['path']}/`",
        f"- **URI tree:** `{ctx.domain_pack.get('uri_tree') or '—'}`",
        f"- **Commands:** `{ctx.domain_pack.get('commands') or '—'}`",
        f"- **Resources:** `{ctx.domain_pack.get('resources') or '—'}`",
        f"- **Views:** `{ctx.domain_pack.get('views') or '—'}`",
    ]
    if ctx.domain_pack.get("operator_registry"):
        lines.append(f"- **Operator registry:** `{ctx.domain_pack['operator_registry']}`")
    if ctx.domain_pack.get("scenario_registry"):
        lines.append(f"- **Scenario registry:** `{ctx.domain_pack['scenario_registry']}`")
    commands_path = ctx.domain_pack.get("commands")
    if commands_path:
        commands = read_yaml(ctx.repo / commands_path)
        for item in commands.get("commands") or []:
            if isinstance(item, dict):
                lines.append(f"- Command `{item.get('name')}` → handler `{item.get('handler_uri')}`")
    return "\n".join(lines)


def _package_label(kind: str) -> str:
    return {
        "operator": "Operator runtime package",
        "system": "System agent package",
        "custom": "Custom agent package",
        "generated": "Generated package",
    }[kind]


def _render_package(ctx: RenderContext) -> str:
    lines = ["", f"## {_package_label(ctx.kind)}", ""]
    if str(ctx.deployment.target_uri).startswith("local://"):
        try:
            package_rel = local_target_to_relative_path(ctx.deployment.target_uri)
            lines.extend(
                [
                    f"- **Path:** `{package_rel.as_posix()}/`",
                    f"- **Uvicorn module:** `{local_target_to_module(ctx.deployment.target_uri)}`",
                ]
            )
        except ValueError:
            lines.append(f"- **Target:** `{ctx.deployment.target_uri}`")
    else:
        lines.append(f"- **Target:** `{ctx.deployment.target_uri}`")

    if ctx.files:
        lines.extend(["", "| File | Role |", "|------|------|"])
        for item in ctx.files:
            lines.append(f"| `{item['path']}` | {item['role']} |")
    return "\n".join(lines)


def _render_deployments(ctx: RenderContext) -> str:
    lines = ["", "## Deployments (registry)", ""]
    if not ctx.all_deployments:
        lines.append(f"- `{ctx.deployment.id}` only")
        return "\n".join(lines)
    lines.extend(["| Deployment id | Target | Health | Status |", "|---------------|--------|--------|--------|"])
    for item in ctx.all_deployments:
        lines.append(
            f"| `{item.id}` | `{item.target_uri}` | `{deployment_health_label(item)}` | `{item.status}` |"
        )
    return "\n".join(lines)


def _render_lifecycle_commands(ctx: RenderContext) -> list[str]:
    return [
        "### Lifecycle (hypervisor)",
        "",
        "```bash",
        f"hypervisor run-agent {ctx.deployment.id} --detach --wait-healthy",
        f"hypervisor inspect-agent {ctx.deployment.id}",
        f"hypervisor describe-agent {ctx.deployment.id} -o output/reports/{ctx.deployment.id}.md",
        f"hypervisor stop-agent {ctx.deployment.id}",
        "```",
        "",
        "### System URIs (dashboard / chat)",
        "",
        "```bash",
        f"uri call view://process/agent/{ctx.deployment.id}/latest",
        f"uri call html://process/agent/{ctx.deployment.id}/latest",
        f"uri call repair://agent/{ctx.deployment.id}/diagnose",
        f"uri call health://agent/{ctx.deployment.id}",
        "```",
        "",
    ]


def _render_http_surface(ctx: RenderContext) -> list[str]:
    if not ctx.run_plan or ctx.is_operator:
        return []
    http_label = {
        "system": "HTTP (system agent)",
        "custom": "HTTP (custom agent)",
        "generated": "HTTP (generated agent)",
    }[ctx.kind]
    backing = capability_backing_note(agent_kind=ctx.kind)
    lines = [
        f"### {http_label}",
        "",
        "```bash",
        " ".join(ctx.run_plan.get("command") or []),
        "```",
        "",
        "| Endpoint | Purpose |",
        "|----------|---------|",
        f"| `GET {ctx.run_plan.get('health_uri')}` | health |",
        f"| `GET {ctx.run_plan.get('card_uri')}` | agent card |",
        "| `GET /capabilities` | capability list |",
    ]
    if ctx.kind == "generated":
        lines.extend(
            [
                "| `GET /resources/read?uri=...` | proxy to Resource Runtime |",
                "| `POST /commands` | dispatch command to Resource Runtime |",
            ]
        )
    lines.extend(["", "### Skills (agent surface)", ""])
    for cap in ctx.contract.get("capabilities") or []:
        if not isinstance(cap, dict):
            continue
        name = cap.get("name")
        invoke = skill_invoke_example(cap, deployment=ctx.deployment)
        detail = cap.get("uri") or cap.get("command") or "—"
        lines.append(f"- `{name}` → `{invoke}` (backs `{detail}`, {backing})")
    return lines


def _render_operator_runtime(ctx: RenderContext) -> list[str]:
    if not ctx.is_operator:
        return []
    runtime = ctx.contract.get("runtime") or {}
    return [
        "### HTTP (operator runtime)",
        "",
        f"- **Command:** `{runtime.get('command', '—')}`",
        f"- **A2A tasks:** `{runtime.get('a2a_tasks_uri', '—')}`",
        f"- **MCP tools:** `{runtime.get('mcp_tools_uri', '—')}`",
        "",
    ]


def _render_invocation(ctx: RenderContext) -> str:
    lines = ["", "## How it is invoked", ""] + _render_lifecycle_commands(ctx)
    lines.extend(_render_http_surface(ctx))
    lines.extend(_render_operator_runtime(ctx))
    return "\n".join(lines)


def _render_architecture(ctx: RenderContext) -> str:
    lines = ["", "## Architecture chain", ""]
    if ctx.is_operator:
        lines.extend(
            [
                "```mermaid",
                "flowchart LR",
                "  O[agents/operators/*.yaml]",
                "  U[uri2ops package]",
                "  D[domains/*/operator_registry]",
                "  O --> U --> D",
                "```",
                "",
                "- **Operator contract** defines schemes, operations, adapters and policy.",
                "- **uri2ops** executes browser/screen/input operations via selected adapter.",
                "- **Domain registries** hold vertical scenarios; operator stays domain-agnostic.",
            ]
        )
    elif ctx.kind == "system":
        lines.extend(
            [
                "```mermaid",
                "flowchart LR",
                "  C[contracts/agents/*.yaml]",
                "  P[agents/system/*]",
                "  H[hypervisor + uri call surface]",
                "  C --> P --> H",
                "```",
                "",
                "- **System agent** lives under `agents/system/*`.",
                "- **Contract YAML** defines observer/controller capabilities.",
                "- **Dashboard/chat** invoke the agent through health, card, and URI views.",
            ]
        )
    elif ctx.kind == "custom":
        lines.extend(
            [
                "```mermaid",
                "flowchart LR",
                "  C[contracts/agents/*.yaml]",
                "  A[agents/custom/* FastAPI]",
                "  H[hypervisor + uri call surface]",
                "  C --> A --> H",
                "```",
                "",
                "- **Custom agent** lives under `agents/custom/*` (generator-safe).",
                "- **Contract YAML** defines capabilities and runtime defaults.",
                "- **Hand-written routes** implement skills and agent-to-agent flows.",
            ]
        )
    else:
        lines.extend(
            [
                "```mermaid",
                "flowchart LR",
                "  C[contracts/agents/*.yaml]",
                "  G[resource-agent-factory generator]",
                "  A[agents/generated/* FastAPI]",
                "  R[Resource Runtime :8000]",
                "  D[domains/*/handlers]",
                "  C --> G --> A",
                "  A -->|read_resource / commands| R",
                "  R --> D",
                "```",
                "",
                "- **Contract YAML** defines capabilities and runtime defaults.",
                "- **Generator** emits `main.py`, `routes.py`, `agent_card.py`, `README.md` (+ Markpact blocks).",
                "- **Thin agent** exposes health/card/skills and forwards business calls to Resource Runtime.",
                "- **Domain handlers** (`python://domains.*.handlers.*`) implement commands when runtime is up.",
            ]
        )
    return "\n".join(lines)


def _render_markpact_blocks(ctx: RenderContext) -> str:
    if not ctx.markpact_blocks:
        return ""
    lines = ["", "## Markpact blocks (from README)", ""]
    for block in ctx.markpact_blocks:
        lines.extend([f"### `{block['label']}`", "", "```yaml", block["body"], "```", ""])
    return "\n".join(lines)


def _render_registry(ctx: RenderContext) -> str:
    lines: list[str] = []
    related_resources = [
        res
        for res in ctx.registry.resources
        if res.owner_agent == ctx.agent_name or ctx.agent_name.split("-")[0] in res.uri
    ]
    if related_resources:
        lines.extend(["", "## Related resources (contract registry)", ""])
        for res in related_resources[:12]:
            lines.append(f"- `{res.uri}` → projection `{res.projection}`, renderer `{res.renderer}`")
    if ctx.agent_caps:
        lines.extend(["", "## Registry index", ""])
        for cap in ctx.agent_caps:
            detail = cap.uri or cap.command or "—"
            lines.append(f"- `{cap.name}` ({cap.type}): `{detail}`")
    return "\n".join(lines)
